PRAGMA foreign_keys = ON;
CREATE TABLE carteirinhas (
id INTEGER PRIMARY KEY AUTOINCREMENT,
numero TEXT NOT NULL UNIQUE,
aluno_id INTEGER UNIQUE NOT NULL,
FOREIGN KEY (aluno_id) REFERENCES alunos(id)
);